spring:
  application:
    name: game-application

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /**

cors:
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  max-age: ${CORS_MAX_AGE:3600}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
